### ISSUE TITLE
small typo in docker readme

### ISSUE THREAD

**Issue by Ryton** [heiner/nle#24]
## 🐛 Bug

There's a small, breaking typo in the docker readme codeblock .

## To Reproduce

1. when running the code as given in the readme:
" $ docker build -file docker/Dockerfile-jammy . -tag nle"
2. it fails with error message:
"docker build" requires exactly 1 argument.

3. Solution (double dashes):
  $ docker build . --file docker/Dockerfile-jammy --tag nle

## Expected behavior
docker build starts => is the case with   #3)

## Environment
WSL2, U22.4.03-LTS 

(Reason i am trying out docker, is that the wheel build fails me :'( )

**Comment by StephenOman** [comment]
Oops! Will fix that.

What's the issue with the build wheel failure? Would be interested to find out what problem you're facing as we want to make NLE as easy to use as possible.

We've also just built a pre-release package that includes some `manylinux` wheels (on TestPyPI) if you are interested in trying those. Further details on that are here: https://github.com/heiner/nle/releases/tag/v1.0.0rc1
